### ISSUE TITLE
nRF91 support?

### ISSUE THREAD

**Issue by thejpster** [nrf-rs/nrf51-hal#21]
I have some changes which add support for the nRF9160 (UART and GPIO I think - not sure I did anything else). If I can get permission to publish them, would you like to add them here, or create an nrf91-hal? Or create an nrf-hal?

I also have github.com/thejpster/nrfxlib-sys, which generates bindings for the Nordic nrfxlib BSD library, which provides the socket API for the nRF9160. Would you like to host that in this org too, or shall I put it in rust-embedded-community?

**Comment by therealprof** [comment]
What's the relation between the nrf91 and nrf51? I'm a bit surprised you're bringing up nrf91 here but if there's some synergy to be had; sure, bring it on. ;)

**Comment by thejpster** [comment]
Well it's all the same IP blocks for i2c, UART, etc, but wired to an M33 and with an LTE radio on the side. Doesn't make sense to duplicate the drivers if we don't need to.

**Comment by thejpster** [comment]
Also, you don't have a meta repo otherwise I would have posted there

**Comment by therealprof** [comment]
> Also, you don't have a meta repo otherwise I would have posted there

True. My assumption would have been that it has more in common with nRF52 than nRF51 but of course that's probably not correct.

There had been plans to merge nrf51-hal and nrf52-hal together some time ago but it never happened due to lack of relevance. Maybe it's time to revisit that idea and add nRF91, too.

Anyway, meanwhile I'd be happy to take PRs adding nRF91 support here.

**Comment by thejpster** [comment]
Added to '52 repo.
